"""Class-name tables for the datasets SkateFormer was trained on.

The NTU RGB+D / NTU RGB+D 120 names follow the official action list (A1-A120); the
NTU-Inter subsets are the mutual-action slices used by `feeders/feeder_ntu_inter.py`
(A50-A60 remapped to 0-10, plus A106-A120 remapped to 11-25 for the 120 version).
NW-UCLA uses the 10 categories of the Northwestern-UCLA Multiview Action 3D benchmark,
in the order produced by `feeders/feeder_ucla.py` (its json label - 1).
"""

NTU120_CLASSES = [
    "drink water",
    "eat meal/snack",
    "brushing teeth",
    "brushing hair",
    "drop",
    "pickup",
    "throw",
    "sitting down",
    "standing up (from sitting position)",
    "clapping",
    "reading",
    "writing",
    "tear up paper",
    "wear jacket",
    "take off jacket",
    "wear a shoe",
    "take off a shoe",
    "wear on glasses",
    "take off glasses",
    "put on a hat/cap",
    "take off a hat/cap",
    "cheer up",
    "hand waving",
    "kicking something",
    "reach into pocket",
    "hopping (one foot jumping)",
    "jump up",
    "make a phone call/answer phone",
    "playing with phone/tablet",
    "typing on a keyboard",
    "pointing to something with finger",
    "taking a selfie",
    "check time (from watch)",
    "rub two hands together",
    "nod head/bow",
    "shake head",
    "wipe face",
    "salute",
    "put the palms together",
    "cross hands in front (say stop)",
    "sneeze/cough",
    "staggering",
    "falling",
    "touch head (headache)",
    "touch chest (stomachache/heart pain)",
    "touch back (backache)",
    "touch neck (neckache)",
    "nausea or vomiting condition",
    "use a fan (with hand or paper)/feeling warm",
    "punching/slapping other person",
    "kicking other person",
    "pushing other person",
    "pat on back of other person",
    "point finger at the other person",
    "hugging other person",
    "giving something to other person",
    "touch other person's pocket",
    "handshaking",
    "walking towards each other",
    "walking apart from each other",
    "put on headphone",
    "take off headphone",
    "shoot at the basket",
    "bounce ball",
    "tennis bat swing",
    "juggling table tennis balls",
    "hush (quiet)",
    "flick hair",
    "thumb up",
    "thumb down",
    "make ok sign",
    "make victory sign",
    "staple book",
    "counting money",
    "cutting nails",
    "cutting paper (using scissors)",
    "snapping fingers",
    "open bottle",
    "sniff (smell)",
    "squat down",
    "toss a coin",
    "fold paper",
    "ball up paper",
    "play magic cube",
    "apply cream on face",
    "apply cream on hand back",
    "put on bag",
    "take off bag",
    "put something into a bag",
    "take something out of a bag",
    "open a box",
    "move heavy objects",
    "shake fist",
    "throw up cap/hat",
    "hands up (both hands)",
    "cross arms",
    "arm circles",
    "arm swings",
    "running on the spot",
    "butt kicks (kick backward)",
    "cross toe touch",
    "side kick",
    "yawn",
    "stretch oneself",
    "blow nose",
    "hit other person with something",
    "wield knife towards other person",
    "knock over other person (hit with body)",
    "grab other person's stuff",
    "shoot at other person with a gun",
    "step on foot",
    "high-five",
    "cheers and drink",
    "carry something with other person",
    "take a photo of other person",
    "follow other person",
    "whisper in other person's ear",
    "exchange things with other person",
    "support somebody with hand",
    "finger-guessing game (playing rock-paper-scissors)",
]
assert len(NTU120_CLASSES) == 120

NTU60_CLASSES = NTU120_CLASSES[:60]

# feeder_ntu_inter.py: A50-A60 -> 0..10
NTU60_INTER_CLASSES = NTU120_CLASSES[49:60]
# ... and additionally A106-A120 -> 11..25
NTU120_INTER_CLASSES = NTU120_CLASSES[49:60] + NTU120_CLASSES[105:120]
assert len(NTU60_INTER_CLASSES) == 11 and len(NTU120_INTER_CLASSES) == 26

NW_UCLA_CLASSES = [
    "pick up with one hand",
    "pick up with two hands",
    "drop trash",
    "walk around",
    "sit down",
    "stand up",
    "donning",
    "doffing",
    "throw",
    "carry",
]
assert len(NW_UCLA_CLASSES) == 10

LABEL_SETS = {
    "ntu60": NTU60_CLASSES,
    "ntu120": NTU120_CLASSES,
    "ntu60_inter": NTU60_INTER_CLASSES,
    "ntu120_inter": NTU120_INTER_CLASSES,
    "nw_ucla": NW_UCLA_CLASSES,
}


def id2label(label_set: str) -> dict:
    """Return an ``{class_id: name}`` mapping for one of :data:`LABEL_SETS`."""
    return {i: name for i, name in enumerate(LABEL_SETS[label_set])}
